version: "3.8"
services:
    mongoserver:
        image:
            mongo:latest
        restart: always
        ports:
            - "27017:27017"
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
        environment: 
            - tp_jwtPrivateKey=mySecureKey
            - tp_newsKey=yb5LR596klIbnSZuhR1DYXst7gDX64Vv7Rr33ubR
            - tp_aesSecret=Secret 123!!!
            - tp_cons_key=F8Rb3OmQlwfwDsMGmicRKWvlw
            - tp_sec_key=nLCmsuy0dM2GIBXbBtV2EdXm8ebnw6YZf7Gwg1ep72eIcAgBri
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"