version: "3.9"
services:
    rabbit:
        image: 
            rabbitmq:3
        networks:
            - app-network
    mongoserver:
        image:
            mongo:latest
        ports:
            - "27017:27017"
        networks:
           - app-network
    nodeserver_1:
        build:
            context: ./app
        ports:
            - "5000"
        env_file:
            - sec.env
        environment: 
            - number=1
        networks:
            - app-network
        depends_on: 
            - rabbit
        restart: on-failure
    nodeserver_2:
        build:
            context: ./app
        ports:
            - "5000"
        env_file:
            - sec.env
        environment: 
            - number=2
        networks:
            - app-network
        depends_on: 
            - rabbit
        restart: on-failure
    nodeserver_3:
        build:
            context: ./app
        ports:
            - "5000"
        env_file:
            - sec.env
        environment: 
            - number=3
        networks:
            - app-network
        depends_on: 
            - rabbit
        restart: on-failure
    nginx:
        build:
            context: ./nginx
        depends_on: 
            - nodeserver_1
            - nodeserver_2
            - nodeserver_3

        ports:
            - 80:80
            - 443:443
        networks:
            - app-network
        restart: on-failure
    
networks:
    app-network:
        driver: bridge
