version: "3.8"
services:
    mongoserver:
        image:
            mongo:latest
        restart: always
        ports:
            - "27017:27017"
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
        environment: 
            - tp_jwtPrivateKey=mySecureKey
            - tp_newsKey=yb5LR596klIbnSZuhR1DYXst7gDX64Vv7Rr33ubR
    server_ws:
        build:
            context: ./server_ws
        ports: 
            - "6969:6969"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"